image: ruby:2.5

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  GEM_PATH: .bundle
  BUNDLER_PATH: .bundle/bin

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .bundle
    - .npm

before_script:
  - apt-get update -y
  - apt-get install -y curl rsync
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
  - source /root/.bashrc
  - nvm install 14
  - chmod +x setup.sh && bash setup.sh

test:
  stage: test
  script:
  - $BUNDLER_PATH/bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - $BUNDLER_PATH/bundle exec jekyll build -d public
  - find public -type f -regex '.*\.\(html\)$' -exec npm run minify-html {} \;
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - public
  only:
  - master
